import Link from 'next/link';
import DashboardLayout from '../../components/dashboard/DashboardLayout';

const ManualJobs = () => {
  return (
    <div className="text-white">
      <h2 className="mb-s3 text-2xl">
        Manually handle tasks that do have been generated by the user
      </h2>
      <div>
        <Link href="/manual/transcription">
          <a className="my-s2 block hover:underline">Go to Transcriptions</a>
        </Link>

        <Link href="/manual/translation">
          <a className="my-s2 block hover:underline">Go to Translations</a>
        </Link>

        <a className="my-s2 block hover:underline">
          <Link href="/manual/dubbing">Go to Dubbing</Link>
        </a>
      </div>
    </div>
  );
};

ManualJobs.getLayout = DashboardLayout;

export default ManualJobs;
